apiVersion: v1
kind: Secret
metadata:
  name: ems-secret
  namespace: ems
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64 for 'root'
  DB_USER: cm9vdA==             # base64 for 'root'
  DB_PASSWORD: cm9vdA==         # base64 for 'root'
